### ISSUE TITLE
Client rewrite

### ISSUE THREAD

**Issue by krazyjakee** [krazyjakee/MystaliaEngine#16]
Redo the animated client in webgl/canvas with pandajs.

**Comment by lordliquid** [comment]
Going to take a swing at this repo, like what I see!

**Comment by krazyjakee** [comment]
I keep coming back to this repo and staring at the code not actually making any advances. I'd be SO grateful if you could make a start. In a few weeks I will be able to fund your progress too.

**Comment by lordliquid** [comment]
I am having some issues getting it to launch. I have just been fixing dependency errors and several little depreciated issues. I'm best with MEAN stack applications.

**Comment by lordliquid** [comment]
I feel like I am close to clearing things up on my end to get up and running.

**Comment by lordliquid** [comment]
Okay, I am stuck on this one. After npm install, I changed _config.coffee to config.coffee. I then launch init.sh (used nodemon as a test also) I am getting this error. 

<code>TypeError: undefined is not a function
  at Object.<anonymous> (C:\MystaliaEngine\MystaliaEngine\server\server.coffee:5
4:14)
  at Object.<anonymous> (C:\MystaliaEngine\MystaliaEngine\server\server.coffee:1
:1)
  at Module._compile (module.js:460:26)
  at Object.exports.run (C:\Users\rober\AppData\Roaming\npm\node_modules\coffee-
script\lib\coffee-script\coffee-script.js:134:23)
  at compileScript (C:\Users\rober\AppData\Roaming\npm\node_modules\coffee-scrip
t\lib\coffee-script\command.js:224:29)
  at compilePath (C:\Users\rober\AppData\Roaming\npm\node_modules\coffee-script\
lib\coffee-script\command.js:174:14)
  at Object.exports.run (C:\Users\rober\AppData\Roaming\npm\node_modules\coffee-
script\lib\coffee-script\command.js:98:20)
  at Object.<anonymous> (C:\Users\rober\AppData\Roaming\npm\node_modules\coffee-
script\bin\coffee:7:41)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3

[nodemon] app crashed - waiting for file changes before starting...
</code>

**Comment by lordliquid** [comment]
Looking at this again.. check out where it's trying to run exports from, my appdata folder.. Need to check my npm globals now..

**Comment by krazyjakee** [comment]
Are you still stuck on anything here?

Also, a note on coffeescript, ideally I'd like to migrate to ES6. As much as I love coffeescript, ES6 offers more.

**Comment by lordliquid** [comment]
I can make an attempt.  There is still so many issues I am running into. I fix one and another one arrives. Fixing the issues with mostly temporary patches. Only to re write it again seems a little redundant at this point. If only it weren't in coffee script ><  lol

**Comment by krazyjakee** [comment]
This should help: http://js2.coffee/

**Comment by lordliquid** [comment]
Ahh I was looking for a converter that would work well. This will do! thanks!
